logging:
  level:
    org:
      springframework:
        web: INFO
spring:
  datasource:
    password: sa
    url: jdbc:h2:mem:testDB
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
